# Generated by Django 4.1.2 on 2022-10-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejected',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 17, 0, 17, 821942)),
            preserve_default=False,
        ),
    ]
