# Generated by Django 4.1.2 on 2022-10-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0002_executedevaluation_zuordnung_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExecutedEvaluation',
            new_name='Auswertungslauf',
        ),
        migrations.RenameModel(
            old_name='Schallursache',
            new_name='LaermursacheAnMesspunkt',
        ),
        migrations.CreateModel(
            name='LaermursacheAnImmissionsort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('immissionsort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsdb.immissionsort')),
            ],
        ),
    ]
