# Generated by Django 4.1.2 on 2022-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0003_alter_detected_options_alter_lrpegel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immissionsort',
            name='utm_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='immissionsort',
            name='utm_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='detected',
            table='tsdb_detected',
        ),
        migrations.AlterModelTable(
            name='lrpegel',
            table='tsdb_lrpegel',
        ),
        migrations.AlterModelTable(
            name='maxpegel',
            table='tsdb_maxpegel',
        ),
        migrations.AlterModelTable(
            name='rejected',
            table='tsdb_rejected',
        ),
        migrations.AlterModelTable(
            name='schallleistungpegel',
            table='tsdb_schallleistungpegel',
        ),
    ]
