# Generated by Django 4.1.2 on 2022-10-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0003_rename_executedevaluation_auswertungslauf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaermursacheAnImmissionsorten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('projekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsdb.projekt')),
            ],
        ),
        migrations.DeleteModel(
            name='LaermursacheAnImmissionsort',
        ),
        migrations.AlterField(
            model_name='lrpegel',
            name='verursacht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsdb.laermursacheanimmissionsorten'),
        ),
    ]
