# Generated by Django 4.1.2 on 2022-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0004_immissionsort_utm_x_immissionsort_utm_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='utm_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projekt',
            name='utm_y',
            field=models.FloatField(default=0.0),
        ),
    ]
