# Generated by Django 4.1.2 on 2022-10-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0004_laermursacheanimmissionsorten_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejection',
            name='messpunkt',
        ),
        migrations.AddField(
            model_name='rejected',
            name='messpunkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tsdb.messpunkt'),
        ),
    ]
