# Generated by Django 4.1.2 on 2022-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0005_projekt_utm_x_projekt_utm_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='name_monatsbericht_excel',
            field=models.CharField(default='N_A', max_length=200),
        ),
    ]
