# Generated by Django 4.1.2 on 2022-10-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0006_detected_berechnet_von_immissionsort_gk_hoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immissionsort',
            name='id_external',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='immissionsort',
            name='name_4_excel',
            field=models.CharField(default='INSERT NAME', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ausbreitstungsfaktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausbreitungskorrektur', models.FloatField(default=0.0)),
                ('immissionsort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsdb.immissionsort')),
                ('messpunkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsdb.messpunkt')),
            ],
        ),
    ]
