# Generated by Django 4.1.2 on 2022-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0006_projekt_name_monatsbericht_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messpunkt',
            name='seriennummer_messstation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
