# Generated by Django 4.1.2 on 2022-10-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0007_immissionsort_id_external_immissionsort_name_4_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messpunkt',
            name='id_external',
            field=models.IntegerField(default=0),
        ),
    ]
