# Generated by Django 4.1.2 on 2022-10-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsdb', '0008_messpunkt_id_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immissionsort',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdb.projekt'),
        ),
        migrations.AlterField(
            model_name='messpunkt',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsdb.projekt'),
        ),
    ]
