DROP TABLE tsdb_lrpegel;
DROP TABLE tsdb_maxpegel;
DROP TABLE tsdb_schallleistungpegel;
DROP TABLE tsdb_detected;
DROP TABLE tsdb_rejected;


CREATE TABLE tsdb_lrpegel (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "time" timestamp with time zone NOT NULL,
    "pegel" double precision NOT NULL,
    "berechnet_von_id" bigint NULL,
    "immissionsort_id" bigint NULL,
    "verursacht_id" bigint NULL,
    FOREIGN KEY("berechnet_von_id") REFERENCES "tsdb_auswertungslauf" ("id") on delete cascade,
    FOREIGN KEY("immissionsort_id") REFERENCES "tsdb_immissionsort" ("id") on delete cascade,
    FOREIGN KEY("verursacht_id") REFERENCES "tsdb_laermursacheanimmissionsorten" ("id") on delete cascade
);


CREATE TABLE "tsdb_maxpegel" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "time" timestamp with time zone NOT NULL,
    "pegel" double precision NOT NULL,
    "berechnet_von_id" bigint NULL,
    "immissionsort_id" bigint NULL,
    FOREIGN KEY("berechnet_von_id") REFERENCES "tsdb_auswertungslauf" ("id") on delete cascade,
    FOREIGN KEY("immissionsort_id") REFERENCES "tsdb_immissionsort" ("id") on delete cascade
);

CREATE TABLE "tsdb_schallleistungpegel" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "time" timestamp with time zone NOT NULL,
    "pegel" double precision NOT NULL,
    "berechnet_von_id" bigint NULL,
    "messpunkt_id" bigint NULL,
    FOREIGN KEY("berechnet_von_id") REFERENCES "tsdb_auswertungslauf" ("id") on delete cascade,
    FOREIGN KEY("messpunkt_id") REFERENCES "tsdb_messpunkt" ("id") on delete cascade
);

CREATE TABLE "tsdb_detected" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "time" timestamp with time zone NOT NULL,
    "dauer" double precision NOT NULL,
    "berechnet_von_id" bigint NULL,
    "messpunkt_id" bigint NULL,
    "typ_id" bigint NULL,
    FOREIGN KEY("berechnet_von_id") REFERENCES "tsdb_auswertungslauf" ("id") on delete cascade,
    FOREIGN KEY("messpunkt_id") REFERENCES "tsdb_messpunkt" ("id") on delete cascade
);

CREATE TABLE "tsdb_rejected" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "berechnet_von_id" bigint NULL,
    "filter_id" bigint NULL,
    "messpunkt_id" bigint NULL,
    "time" timestamp with time zone NOT NULL,
    FOREIGN KEY("berechnet_von_id") REFERENCES "tsdb_auswertungslauf" ("id") on delete cascade,
    FOREIGN KEY("messpunkt_id") REFERENCES "tsdb_messpunkt" ("id") on delete cascade
);


SELECT create_hypertable('tsdb_rejected', 'time');

SELECT create_hypertable('tsdb_detected', 'time');

SELECT create_hypertable('tsdb_schallleistungpegel', 'time');

SELECT create_hypertable('tsdb_maxpegel', 'time');

SELECT create_hypertable('tsdb_lrpegel', 'time');

/*
ALTER TABLE order_details
  ADD order_date date,
  ADD quantity integer;
  */